apiVersion: v1
kind: ConfigMap
metadata:
  name: amn-amro-backend-config
  labels:
    app.kubernetes.io/name: amn-amro-backend
data:
  INPUT_FILE_PATH: /data/Input.txt
  OUTPUT_FILE_PATH: /data/Output.csv
  KAFKA_BOOTSTRAP_SERVERS: kafka:9092
  KAFKA_TRANSACTION_TOPIC: transactions
  KAFKA_DEAD_LETTER_TOPIC: transactions.dlq
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: amn-amro-frontend-config
  labels:
    app.kubernetes.io/name: amn-amro-frontend
data:
  BACKEND_BASE_URL: http://amn-amro-backend:8080
